import{i as l,S as m}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const c="/goit-js-hw-11/assets/bi_x-octagon-ddf7add7.svg",n={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function u(){n.loader.classList.toggle("hidden")}n.form.addEventListener("submit",d);function g(o){const t=new URLSearchParams({key:"42132229-e88b92984f0d2a7001cb07c65",image_type:"photo",orientation:"horizontal",safesearch:"true",q:o}),s="https://pixabay.com/api"+"?"+t;return fetch(s).then(e=>{if(e.ok)return e.json();throw new Error(e.status)})}function d(o){o.preventDefault(),u();const t=o.target.elements.query.value;g(t).then(i=>{if(u(),t===""){l.warning({message:"Sorry, you forgot to enter a search term. Please try again!",position:"topRight",messageSize:"16px",timeout:2e3});return}else parseInt(i.totalHits)>0?y(i.hits):(n.gallery.innerHTML="",l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:c,color:"white",timeout:2e3}))}).catch(i=>{l.error({message:"Error",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:c,color:"white",timeout:2e3})}),o.target.reset()}function f({largeImageURL:o,webformatURL:t,tags:i,likes:s,views:e,comments:r,downloads:a}){return`<a class="gallery-link" href="${o}"><img class="gallery-image" src="${t}" alt="${i}"/>
  <div class="gallery-review">
  <div class="gallery-review-item"><b>Likes</b> <span>${s}</span></div>
  <div class="gallery-review-item"><b>Views</b> <span>${e}</span></div>
  <div class="gallery-review-item"><b>Comments</b> <span>${r}</span></div>
  <div class="gallery-review-item"><b>Downloads</b> <span>${a}</span></div>
  </div></a>
    `}let p=new m(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function y(o){const t=o.map(f).join("");n.gallery.innerHTML=t,p.refresh()}
//# sourceMappingURL=commonHelpers.js.map
