import{i as l,S as c}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const d="/goit-js-hw-11/assets/bi_x-octagon-ddf7add7.svg",s={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")};s.loader.style.visibility="hidden";s.form.addEventListener("submit",m);function u(o){const t=new URLSearchParams({key:"42132229-e88b92984f0d2a7001cb07c65",image_type:"photo",orientation:"horizontal",safesearch:"true",q:o}),a="https://pixabay.com/api/"+"?"+t;return fetch(a).then(e=>e.json()).catch(e=>{console.log(e)})}function m(o){o.preventDefault(),s.loader.style.visibility="visible";const t=o.target.elements.query.value;u(t).then(i=>{if(s.loader.style.visibility="hidden",t===""){s.gallery.innerHTML="";return}else parseInt(i.totalHits)>0?g(i.hits):(s.gallery.innerHTML="",l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red",messageColor:"white",messageSize:"16px",iconColor:"white",iconUrl:d,color:"white",timeout:2e3}))}),o.target.reset()}function y({largeImageURL:o,webformatURL:t,tags:i,likes:a,views:e,comments:r,downloads:n}){return`<a class="gallery-link" href="${o}"><img class="gallery-image" src="${t}" alt="${i}"/>
  <div class="gallery-review">
  <div class="gallery-review-item"><b>Likes</b> <span>${a}</span></div>
  <div class="gallery-review-item"><b>Views</b> <span>${e}</span></div>
  <div class="gallery-review-item"><b>Comments</b> <span>${r}</span></div>
  <div class="gallery-review-item"><b>Downloads</b> <span>${n}</span></div>
  </div></a>
    `}let f=new c(".gallery a",{showCounter:!1,captionDelay:250,captions:!0,captionsData:"alt",captionPosition:"bottom"});function g(o){const t=o.map(y).join("");s.gallery.innerHTML=t,f.refresh()}
//# sourceMappingURL=commonHelpers.js.map
